esphome:
  name: gatekeeper

logger: 
  level: VERY_VERBOSE

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

ota:
  password: !secret password

servo:
  - id: my_servo
    output: pwm_out

output:
  - platform: ledc
    pin: 25
    id: pwm_out
    frequency: 50 Hz


sensor:
  - platform: uptime
    name: "uptime"

web_server:
  port: 80
  auth:
    username: !secret username
    password: !secret password

switch:
  - platform: gpio
    pin: 26
    id: gate
    name: "gate"
    on_turn_on:
      - switch.turn_on: gate
      - servo.write: 
          id: my_servo
          level: 0.0%
      - delay: 5s
      - switch.turn_off: gate
    on_turn_off:
      - switch.turn_off: gate
      - servo.write: 
          id: my_servo
          level: -100.0%
  - platform: restart
    name: reboot
